config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users, path: '',
    path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile' },
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  resources :photos

  resources :tours do
    resources :reservations, only: [:create] do
      collection do
        get 'preload'
        get 'preview'
      end
    end

    resources :reviews, only: [:create, :destroy]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  get '/search' => 'pages#search'
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f.first.to_s.gsub('alert','error').gsub('notice','info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if(!user_signed_in?) %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: 'img-circle avatar-small' %>&nbsp;
              <%= current_user.first_name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Your listings', tours_path %></li>
              <li><%= link_to 'Your reservations', your_reservations_path %></li>
              <li><%= link_to 'Your trips', your_trips_path %></li>
              <li><a href="#">Wish list</a></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Account setting</a></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>

        <li>
          <%= link_to conversations_path do %>
            <i class="fa fa-envelope-o"></i> Messages
          <% end %>
        </li>

        <li>
          <%= link_to new_tour_path do %>
            <i class="fa fa-home fa-lg"></i> Become a guide
          <% end %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>