config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users, path: '',
    path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile' },
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  resources :photos

  resources :tours do
    resources :reservations, only: [:create] do
      collection do
        get 'preload'
        get 'preview'
      end
    end

    resources :reviews, only: [:create, :destroy]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  get '/search' => 'pages#search'
end

app/views/pages/home.html.erb
<%= form_tag search_path, method: :get do %>
  <div class="row">
    <div class="col-md-6">
      <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= submit_tag "Search", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<br />

<div class="text-center">
  <h2>Just for the weekend</h2>
  <p>Discover new, inspiring places</p>
</div>

<br />

<div class="row">
  <div class="col-md-4 col-sm-12">
    <%= link_to search_path(search:'new york') do %>
      <div class="discovery-card" style="background-image: url('/assets/New_York.jpg')">
        <div class="va-container">
          <div class="va-middle text-center">
            <h2><strong>New York</strong></h2>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-4 col-sm-6">
    <%= link_to search_path(search:'london') do %>
      <div class="discovery-card" style="background-image: url('/assets/London.jpg')">
        <div class="va-container">
          <div class="va-middle text-center">
            <h2><strong>London</strong></h2>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-4 col-sm-6">
    <%= link_to search_path(search:'berlin') do %>
      <div class="discovery-card" style="background-image: url('/assets/Berlin.jpg')">
        <div class="va-container">
          <div class="va-middle text-center">
            <h2><strong>Berlin</strong></h2>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br />

<div class="text-center">
  <h2>Explore the world</h2>
  <p>See where people are traveling</p>
</div>

<div class="row">
  <% @tours.each do |tour| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag tour.photos[0].image.url(:medium) if tour.photos.length > 0 %>
        </div>
        <div class="panel-body">
          <%= image_tag avatar_url(tour.user), class: "img-circle avatar-small" %>&nbsp;
          <%= link_to tour.title, tour %>
        </div>
      </div>
    </div>

  <% end %>
</div>

<script>
$(function() {
  $("#start_date").datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#end_date').datepicker("option", "minDate", selected);
      $('#end_date').attr('disabled', false);
    }
  });

  $("#end_date").datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#start_date').datepicker("option", "maxDate", selected);
    }
  });
})
</script>

app/views/pages/search.html.erb
<div id="wrapper">

  <div id="sidebar">
    <div id="widget" class="sticky">
    </div>
    <div class="sticky-stopper"></div>
  </div>

  <div id="article">

    <div class="row">

      <div class="col-md-12">

        <%= search_form_for @search, url: search_path do |f| %>

          <div class="row">
            <div class="col-md-3">
              <%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control" %>
            </div>
            <div class="col-md-3">
              <%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: "form-control" %>
            </div>
            <div class="col-md-3">
              <%= f.text_field :price_gteq, placeholder: "Min Price", class: "form-control" %>
            </div>
            <div class="col-md-3">
              <%= f.text_field :price_lteq, placeholder: "Max Price", class: "form-control" %>
            </div>
          </div>

          <hr>

          <div class="row">
            <div class="col-md-4">
              <%= check_box_tag "q[tour_type_eq_any][]", "Entire" %> Entire tour
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[tour_type_eq_any][]", "Private" %> Private tour
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[tour_type_eq_any][]", "Shared" %> Shared tour
            </div>
          </div>

          <hr>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label>Accommodate</label>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <label>Bedtours</label>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <label>Bathtours</label>
              </div>
            </div>
          </div>

          <hr>

          <div class="row">
            <div class="col-md-4">
              <%= check_box_tag "q[is_tv_eq]", true %> TV
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[is_kitchen_eq]", true %> Kitchen
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[is_internet_eq]", true %> Internet
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[is_heating_eq]", true %> Heating
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[is_air_eq]", true %> Air Conditioning
            </div>
          </div>

          <br>

          <div class="row">
            <%= f.submit "Search", class: "btn btn-primary" %>
          </div>

        <% end %>

        <hr>

        <div class="row">
          <% @arrTours.each do |tour| %>
            <div class="col-md-6">
              <div class="panel panel-default">
                <div class="panel-heading preview">
                  <%= image_tag tour.photos[0].image.url(:medium) if tour.photos.length > 0 %>
                </div>
                <div class="panel-body">
                  <%= link_to tour.title, tour %>
                </div>
              </div>
            </div>

          <% end %>
        </div>

      </div>


    </div>

  </div>

</div>

<script>
$(function() {
  $("#start_date").datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#end_date').datepicker("option", "minDate", selected);
      $('#end_date').attr('disabled', false);
    }
  });

  $("#end_date").datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#start_date').datepicker("option", "maxDate", selected);
    }
  });
})
</script>

<script>
$( document ).ready(function() {
  console.log( "document ready!" );

  var $sticky = $('.sticky');
  var $stickyrStopper = $('.sticky-stopper');
  if (!!$sticky.offset()) { // make sure ".sticky" element exists

    var generalSidebarHeight = $sticky.innerHeight();
    var stickyTop = $sticky.offset().top;
    var stickOffset = 0;
    var stickyStopperPosition = $stickyrStopper.offset().top;
    var stopPoint = stickyStopperPosition - generalSidebarHeight - stickOffset;
    var diff = stopPoint + stickOffset;

    $(window).scroll(function(){ // scroll event
      var windowTop = $(window).scrollTop(); // returns number

      if (stopPoint < windowTop) {
        $sticky.css({ position: 'absolute', top: diff });
      } else if (stickyTop < windowTop+stickOffset) {
        $sticky.css({ position: 'fixed', top: stickOffset });
      } else {
        $sticky.css({position: 'absolute', top: 'initial'});
      }
    });

  }
});
</script>

<script>
function initMap() {
  var uluru = {lat: <%= @arrTours.first.try(:latitude) || 35.6592247 %>, lng: <%= @arrTours.first.try(:longitude) || 139.6993015 %>};
  var map = new google.maps.Map(document.getElementById('widget'), {
    zoom: 14,
    center: uluru
  });

  <% @arrTours.each do |tour| %>
      var marker = new google.maps.Marker({
        position: {lat: <%= tour.latitude %>, lng: <%= tour.longitude %> },
        map: map,
        title: "<%= tour.title %>"
      });
<% end %>
}
</script>
<script async defer
                     src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDZdhttLLtHOU3U0jwzU7uzDWGu1OnLmYo&callback=initMap">
</script>