config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users, path: '',
    path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile' },
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  resources :photos

  resources :tours do
    resources :reservations, only: [:create] do
      collection do
        get 'preload'
        get 'preview'
      end
    end

    resources :reviews, only: [:create, :destroy]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  get '/search' => 'pages#search'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :tour
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :authenticate_user!

  def preload
    tour = Tour.find(params[:tour_id])
    today = Date.current
    reservations = tour.reservations.where('start_date >= ? OR end_date >= ?', today, today)

    render json: reservations
  end

  def preview
    return render(text: '', status: 400) unless params[:start_date].present? && params[:end_date].present?
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date)
    }

    render json: output
  end

  def create
    @reservation = current_user.reservations.create(reservation_params)

    redirect_to @reservation.tour, notice: 'Your reservation has been created...'
  end

  def your_trips
    @reservations = current_user.reservations
  end

  def your_reservations
    @tours = current_user.tours.eager_load(:reservations)
  end

  private

  def is_conflict(start_date, end_date)
    tour = Tour.find(params[:tour_id])
    check = tour.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
    check.exists?
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :price, :total, :tour_id)
  end
end

app/views/reservations/_form.html.erb
<%= form_for([@tour, @tour.reservations.new]) do |f| %>

  <div class="row">
    <div class="col-md-12 price_tag">
      ¥<span><%= @tour.price %></span>
      <span class="pull-right">Per person</span>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <label>Check In</label>
      <%= f.text_field :start_date, readonly:true, placeholder: 'Start date', class: 'form-control' %>
    </div>
    <div class="col-md-6">
      <label>Check Out</label>
      <%= f.text_field :end_date, readonly:true, placeholder: 'End date', class: 'form-control', disabled: 'true' %>
    </div>
  </div>

  <%= f.hidden_field :tour_id, value: @tour.id %>
  <%= f.hidden_field :price, value: @tour.price %>
  <%= f.hidden_field :total, id: 'reservation_total' %>

  <h4><span id="message"></span></h4>

  <div id="preview" style="display: none;">
    <table class="reservation-table">
      <tbody>
        <tr>
          <td>Day(s)</td>
          <td><span id="reservation_days"></span></td>
        </tr>
        <tr>
          <td>Total</td>
          <td>¥<span id="reservation_sum"></span></td>
        </tr>
      </tbody>
    </table>
  </div>

  <br />
  <%= f.submit 'Book now', id: 'btn_book', class: 'btn btn-primary wide', disabled: true %>
<% end %>

<script>

  function unavailable(date) { 
    dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
    return [$.inArray(dmy, unavalaibleDates) == -1];
  }

  function refreshReservationDisplay() {
    var start_date = $('#reservation_start_date').datepicker('getDate');
    var end_date = $('#reservation_end_date').datepicker('getDate');

    var input = {
      'start_date': start_date,
      'end_date': end_date,
    };

    $.ajax({
      url: "<%= preview_tour_reservations_path(@tour.id) %>",
      data: input,
      success: function(data) {
        if (data.conflict){
          $('#message').text('This date range is not available.');
          $('#preview').hide();
          $('#btn_book').attr('disabled', true);
        } else {
          $('#message').text('This date range is OK.');
          $('#preview').show();
          $('#btn_book').attr('disabled', false);

          var days = (end_date - start_date)/1000/60/60/24 + 1;
          var total = days * <%= @tour.price %>;
          $('#reservation_days').text(days);
          $('#reservation_sum').text(total);
          $('#reservation_total').val(total);
        }
      }
    });
  }

  $(function() {
    unavalaibleDates = [];

    $.ajax({
      url: "<%= preload_tour_reservations_path(@tour.id) %>",
      dataType: 'json',
      success: function(data) {
        $.each(data, function(arrID, arrValue) {
          for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
            unavalaibleDates.push($.datepicker.formatDate('d-m-yy', d));
          }
        });
      }
    });

    $('#reservation_start_date').datepicker({
      dateFormat: 'yy-mm-dd',
      minDate: 0,
      maxDate: '3m',
      beforeShowDay: unavailable,
      onSelect: function(selected) {
        $('#reservation_end_date').datepicker("option", "minDate", selected);
        $('#reservation_end_date').attr('disabled', false)
        refreshReservationDisplay();
      }
    });
    $('#reservation_end_date').datepicker({
      dateFormat: 'yy-mm-dd',
      minDate: 0,
      maxDate: '3m',
      beforeShowDay: unavailable,
      onSelect: function(selected) {
        $('#reservation_start_date').datepicker("option", "maxDate", selected);
        refreshReservationDisplay();
      }
    });
  });
</script>

app/views/reservations/your_reservations.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Your Listing", tours_path, class: "sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link active" %></li>
            <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                Your Reservations
            </div>
            <div class="panel-body">
              <% @tours.each do |tour| %>

                <% tour.reservations.each do |reservation| %>
                    <div class="row">
                        <div class="col-md-2">
                          <%= reservation.start_date.strftime('%v') %>
                        </div>
                        <div class="col-md-6">
                          <%= link_to tour_path(reservation.tour) do %>
                            <%= image_tag first_photo_url(reservation.tour, :thumb) %>
                          <% end %>
                        </div>
                        <div class="col-md-2">
                          <%= link_to user_path(reservation.user) do %>
                          <%= image_tag avatar_url(reservation.user), class: 'img-circle avatar-medium' %>
                          <% end %>
                        </div>
                        <div class="col-md-2 right">
                          <h4>¥<%= reservation.total %></h4>
                        </div>
                    </div>
                    <hr>
                <% end %>
              <% end %>
            </div>
        </div>
    </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Your Listing", tours_path, class: "sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link active" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                Listings
            </div>
            <div class="panel-body">

                <% @reservations.each do |reservation| %>
                    <div class="row">
                        <div class="col-md-2">
                          <%= reservation.start_date.strftime('%v') %>
                        </div>
                        <div class="col-md-6">
                          <%= link_to tour_path(reservation.tour) do %>
                            <%= image_tag first_photo_url(reservation.tour, :thumb) %>
                          <% end %>
                        </div>
                        <div class="col-md-2">
                          <%= link_to user_path(reservation.tour.user) do %>
                          <%= image_tag avatar_url(reservation.tour.user), class: 'img-circle avatar-medium' %>
                          <% end %>
                        </div>
                        <div class="col-md-2 right">
                          <h4>¥<%= reservation.total %></h4>
                        </div>
                    </div>
                    <hr>
                <% end %>

            </div>
        </div>
    </div>
</div>